import {applyTheme,initialTheme} from '../src/theme';
applyTheme(initialTheme());
import {useState,useRef} from 'react';import {createRoot} from 'react-dom/client';
import {PdfReader} from '../src/PdfReader';import type {PdfReaderHandle} from '../src/PdfReader';
import {emptyReader,pdfExcerpt} from '../src/pdfReaderState';import type {PdfReaderData} from '../src/pdfReaderState';
import '../src/styles.css';
import data from './pdf-fixture.json';import '../src/library.css';
const report=(value:object)=>{console.log(JSON.stringify(value));(window as unknown as {webkit?:{messageHandlers:{result:{postMessage:(v:object)=>void}}}}).webkit?.messageHandlers?.result?.postMessage(value);
(window as unknown as {__TAURI_INTERNALS__?:{invoke:(cmd:string,args:object)=>Promise<unknown>}}).__TAURI_INTERNALS__?.invoke('pdf_probe_report',{value}).catch(console.error);};
let stored:PdfReaderData=emptyReader(),fail=false,flushFailed=false;
function App(){const handle=useRef<PdfReaderHandle>(null),[mounted,setMounted]=useState(true),[readonly,setReadonly]=useState(false),[notes,setNotes]=useState(''),[revision,setRevision]=useState(0);
 return <main style={{margin:20,fontFamily:'-apple-system, sans-serif'}}><h2>Orbit · PDF 阅读器</h2><div style={{display:'flex',gap:12,marginBottom:12}}><button id="toggle" onClick={()=>void handle.current?.flush().then(()=>setMounted(false)).catch(e=>{flushFailed=true;report({stage:'flush-failed',message:String(e)});})}>关闭</button><button id="reopen" onClick={()=>setMounted(true)}>重新打开</button><button id="readonly" onClick={()=>setReadonly(v=>!v)}>只读</button><button id="fail" onClick={()=>{fail=!fail;}}>切换保存失败</button><span id="revision">{revision}</span></div>{mounted&&<PdfReader ref={handle} data={data} initial={stored} readOnly={readonly} persist={async value=>{if(fail)throw Error('Fixture disk full');if(value.revision!==stored.revision)throw Error('Fixture CAS conflict');stored={...value,revision:value.revision+1};return stored;}} onSaved={value=>setRevision(value.revision)} onExcerpt={a=>setNotes(s=>s+pdfExcerpt('Reader fixture','12345678-1234-1234-1234-123456789abc',a))}/>}<textarea id="notes" value={notes} readOnly style={{width:'100%',height:80,marginTop:15}}/></main>;
}
createRoot(document.getElementById('root')!).render(<App/>);
const wait=async(predicate:()=>unknown,label:string)=>{for(let i=0;i<160;i++){if(predicate())return;await new Promise(r=>setTimeout(r,100));}throw Error(`Timeout ${label}`);};
const button=(label:string)=>document.querySelector<HTMLButtonElement>(`button[aria-label="${label}"]`)!;
const input=(element:HTMLInputElement|HTMLTextAreaElement,value:string)=>{Object.getOwnPropertyDescriptor(element instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value')!.set!.call(element,value);element.dispatchEvent(new Event('input',{bubbles:true}));};
report({stage:'fixture-entry',url:location.href,hidden:document.hidden});requestAnimationFrame(()=>report({stage:'raf'}));
if(location.search.includes('run'))void (async()=>{try{
 await wait(()=>document.querySelectorAll('.textLayer span').length===2,'two text layers');report({stage:'reader-rendered',canvas:document.querySelectorAll('.page canvas').length});
 input(document.querySelector('[aria-label="搜索 PDF 正文"]')!,'Orbit');await wait(()=>document.querySelector('.pdf-find')?.textContent?.includes('1 / 1'),'search');
 button('PDF 目录').click();await wait(()=>document.querySelector('.pdf-outline-row'),'outline');(document.querySelector('.pdf-outline-row') as HTMLButtonElement).click();await wait(()=>(document.querySelector('[aria-label="PDF 页码"]') as HTMLInputElement).value==='2','outline navigation');
 const span=document.querySelector('[data-page-number="2"] .textLayer span')!,range=document.createRange();range.selectNodeContents(span);const selection=window.getSelection()!;selection.removeAllRanges();selection.addRange(range);document.dispatchEvent(new Event('selectionchange'));await wait(()=>!(document.querySelector('.pdf-highlight-button') as HTMLButtonElement).disabled,'selection');(document.querySelector('.pdf-highlight-button') as HTMLButtonElement).click();
 await wait(()=>stored.annotations.length===1,'highlight saved');const annotation=stored.annotations[0];if(annotation.page!==2||annotation.rects.some(r=>r[0]<10||r[1]<20||r[2]>490||r[3]>640))throw Error('Rotated PDF coordinates invalid');
 button('放大 PDF').click();await wait(()=>button('PDF 适合宽度').textContent?.includes('125'),'zoom');
 await wait(()=>{const highlight=document.querySelector('[data-page-number="2"] .orbit-pdf-highlights span'),text=document.querySelector('[data-page-number="2"] .textLayer span');if(!highlight||!text)return false;const range=document.createRange();range.selectNodeContents(text);const a=highlight.getBoundingClientRect(),b=range.getClientRects()[0];return b&&Math.abs(a.left-b.left)<4&&Math.abs(a.top-b.top)<4&&Math.abs(a.width-b.width)<4&&Math.abs(a.height-b.height)<4;},'rotated highlight alignment after zoom');
 input(document.querySelector('.pdf-annotation textarea')!,'Comment from fixture');await wait(()=>stored.annotations[0]?.comment==='Comment from fixture','comment saved');button('批注加入 Markdown 备注').click();await wait(()=>(document.getElementById('notes') as HTMLTextAreaElement).value.includes('?page=2&annotation='),'markdown backlink');
 report({stage:'annotations',page:annotation.page,rects:annotation.rects,text:annotation.text});
 (document.getElementById('fail') as HTMLButtonElement).click();input(document.querySelector('.pdf-annotation textarea')!,'Retained after failure');await wait(()=>document.querySelector('.pdf-save-error'),'failed save');(document.getElementById('toggle') as HTMLButtonElement).click();await wait(()=>flushFailed,'flush rejected');if(!document.querySelector('.pdf-reader'))throw Error('Failed reader unmounted');if((document.querySelector('.pdf-annotation textarea') as HTMLTextAreaElement).value!=='Retained after failure')throw Error('Lost failed input');
 (document.getElementById('fail') as HTMLButtonElement).click();(document.querySelector('.pdf-save-error button') as HTMLButtonElement).click();await wait(()=>!document.querySelector('.pdf-save-error'),'retry');
 (document.getElementById('readonly') as HTMLButtonElement).click();await wait(()=>button('删除 PDF 批注').disabled,'readonly');(document.getElementById('readonly') as HTMLButtonElement).click();
 button('PDF 缩略图').click();await wait(()=>document.querySelectorAll('.pdf-thumbnail canvas').length===2,'thumbnails');
 for(let i=0;i<2;i++){(document.getElementById('toggle') as HTMLButtonElement).click();await wait(()=>!document.querySelector('.pdf-reader'),'cleanup');(document.getElementById('reopen') as HTMLButtonElement).click();await wait(()=>document.querySelectorAll('.textLayer span').length===2,'reopen');}
 button('PDF 批注').click();await wait(()=>document.querySelector('.pdf-annotation textarea'),'restored annotation');if((document.querySelector('.pdf-annotation textarea') as HTMLTextAreaElement).value!=='Retained after failure')throw Error('Saved annotation not restored');
 report({stage:'complete',checks:'search outline rotated selection comments markdown failure retry readonly thumbnails remount',revision:stored.revision});
}catch(error){report({stage:'error',message:String(error),stack:error instanceof Error?error.stack:''});}})();
