import {applyTheme,initialTheme} from '../src/theme';
applyTheme(initialTheme());
// Isolated UI fixture: all operations stay in React memory; never calls an executor or user Store.
import {useState} from 'react';import {createRoot} from 'react-dom/client';
import {TaskWorkspace} from '../src/TaskWorkspace';import {isAccepted} from '../src/model';import type {Task} from '../src/model';import {previewExecutors} from '../src/executors';
import '../src/styles.css';import '../src/workspace.css';
// Simulate the menu's constrained height when the preview host ignores viewport overrides.
if(new URLSearchParams(location.search).has('short-menu')){const style=document.createElement('style');style.textContent='.task-context-menu{max-height:120px!important}';document.head.append(style);}
const base:Task={id:'review',title:'比较本地知识库工具',prompt:'比较 Zotero 与 DEVONthink 的 PDF 阅读、标签和文档链接，给出个人工作流建议。',scene:'research',provider:'codex',status:'completed',createdAt:1,startedAt:1,finishedAt:2,runId:'run-review',threadId:'thread',turnId:'turn',revision:1,phase:1,nodes:[{id:'lead',name:'Codex',role:'主 Agent',model:'CLI 默认模型',status:'completed',summary:'已汇总三方结论',output:'已完成工具比较。',parentId:null},{id:'researcher',name:'researcher',role:'子 Agent',model:'模型未返回',status:'completed',summary:'PDF 阅读器调研完成',output:'PDF.js 支持文本层与批注。',parentId:'lead'}],events:[{id:'event',at:1,kind:'system',agent:'工作台',text:'已保存真实执行器事件'}],approvals:[],artifacts:[{id:'doc',name:'工具比较.md',kind:'markdown',createdAt:2,content:'# 工具比较\n\n|能力|Zotero|DEVONthink|\n|---|---|---|\n|PDF 阅读|强|强|\n|资料组织|分类与标签|标签与智能分组|\n\n建议按研究和归档需求选择。'}],tokens:null};
if(new URLSearchParams(location.search).has('long')){base.prompt+='\n\n'+('请检查离线资料库的操作与交付流程。\n'.repeat(20));base.artifacts[0].content='# 长消息报告\n\n'+('这段测试内容用于验证折叠、展开与复制原始 Markdown 全文。\n\n'.repeat(30))+'[原始链接](https://example.com)\n\n全文末尾标记';}
const initial=[{...base,id:'todo',title:'制定下周阅读计划',prompt:'根据现有资料，整理五天阅读计划。',status:'queued',runId:null,turnId:null,threadId:null,nodes:[],artifacts:[]},{...base,id:'running',title:'整理文献笔记',prompt:'总结三篇文献的研究方法与结论。',provider:'qoder',status:'running',runId:'run-running',artifacts:[],capabilities:{resume:false,steer:false,input:false,interrupt:true,agentHistory:false},nodes:[{...base.nodes[0],status:'running',name:'Qoder',output:'正在整理研究方法。'}]},base,{...base,id:'done',title:'写作大纲',scene:'writing',prompt:'整理个人知识管理文章大纲。',acceptance:{runId:base.runId,turnId:base.turnId,artifactIds:['doc']}},{...base,id:'waiting',title:'补充市场功能比较',queue:{requestId:'request',order:1,nextRunId:'next',state:'pending',error:null,action:{kind:'continue',runId:base.runId,turnId:base.turnId,text:'补充当前产品的离线功能。'}}}] as Task[];
if(new URLSearchParams(location.search).has('dense')){
 base.nodes.push(...['technical','challenger'].map(id=>({...base.nodes[1],id,name:id,output:'Agent 详细输出。\n\n'.repeat(80)})));
 initial.push(...Array.from({length:24},(_,i)=>({...base,id:'extra-'+i,title:'资料整理任务 '+(i+1),status:'queued' as const,nodes:[],artifacts:[],runId:null,threadId:null,turnId:null})));
}
function Fixture(){const [tasks,setTasks]=useState(initial),[id,setId]=useState('review'),[drafts,setDrafts]=useState<Record<string,string>>({}),[queue,setQueue]=useState({paused:false,reason:null as string|null}),[operation,setOperation]=useState('尚未操作');const task=tasks.find(t=>t.id===id)!;
 const update=(id:string,fn:(t:Task)=>Task)=>setTasks(all=>all.map(t=>t.id===id?{...fn(t),revision:t.revision+1}:t));
 return <div className="fixture-root" style={{padding:'26px',maxWidth:1480,margin:'auto'}}><h1 style={{fontSize:26,margin:'0 0 6px'}}>任务工作台</h1><p style={{color:'#86868b',fontSize:13,margin:'0 0 26px'}}>隔离交互检查 · 数据与命令只存在内存</p><TaskWorkspace tasks={tasks} selected={task} queue={queue} draft={drafts[id]||''} busy={false} desktop={true} executors={previewExecutors} onSelect={t=>setId(t.id)} onChange={text=>setDrafts(all=>({...all,[id]:text}))} onDuplicate={target=>setOperation('复制为新任务 '+target.id)} onStart={t=>{update(t.id,t=>({...t,queue:{requestId:'request-'+t.id,order:Date.now(),nextRunId:'next-'+t.id,state:'pending',error:null,action:{kind:'start'}}}));setOperation('排队启动 '+t.id);}} onCancel={t=>{update(t.id,t=>({...t,queue:null}));setOperation('取消排队 '+t.id);}} onAccept={t=>{update(t.id,t=>({...t,acceptance:{runId:t.runId,turnId:t.turnId,artifactIds:t.artifacts.map(a=>a.id)}}));setOperation('验收 '+t.id);}} onPause={paused=>{setQueue({paused,reason:paused?'手动暂停':null});setOperation(paused?'暂停队列':'恢复队列');}} onSend={()=>{setOperation('继续交付 '+id+' '+drafts[id]);update(id,t=>({...t,queue:{requestId:'continue',nextRunId:'next',order:Date.now(),state:'pending',error:null,action:{kind:'continue',runId:t.runId,turnId:t.turnId,text:drafts[id]}}}));setDrafts(all=>({...all,[id]:''}));}} onSteer={()=>{setOperation('steer '+id+' '+drafts[id]);setDrafts(all=>({...all,[id]:''}));}} onOpen={a=>setOperation('打开 '+a.name)} onArchive={target=>{if(isAccepted(target)){setTasks(all=>all.filter(t=>t.id!==target.id));if(id===target.id)setId('todo');setOperation('归档 '+target.id);}}} onStop={target=>setOperation('中断 '+target.id)} onSync={()=>setOperation('同步 '+id)} onAnswer={()=>setOperation('答复 '+id)}/><p role="status" style={{fontSize:12,color:'#86868b'}}>最近操作：{operation}</p><button style={{fontSize:12}} onClick={()=>{update('running',t=>({...t,provider:'codex',capabilities:{resume:true,steer:true,input:true,interrupt:true,agentHistory:true}}));setId('running');setOperation('切换为支持运行补充的 Codex fixture');}}>切换运行补充 fixture</button></div>;
}
createRoot(document.getElementById('root')!).render(<Fixture/>);
// Diagnostic trace for native input, deliberately outside production components.
if(new URL(location.href).searchParams.has('trace')) {
const trace=document.createElement('pre');trace.setAttribute('aria-label','拖动事件记录');document.body.append(trace);
for(const kind of ['pointerdown','pointerup','dragstart','dragenter','dragover','drop','dragend'])window.addEventListener(kind,event=>{const drag=event as DragEvent;trace.textContent+=(JSON.stringify({type:kind,target:(event.target as HTMLElement)?.className,types:drag.dataTransfer?Array.from(drag.dataTransfer.types):[],prevented:event.defaultPrevented})+'\n');});

}

if(new URLSearchParams(location.search).has('theme-state')){const badge=document.createElement('div');badge.className='nav-item';badge.innerHTML='<span>待介入状态样本</span><span class="attention-count">3</span>';document.body.append(badge);}

if(new URLSearchParams(location.search).has('layout')){const style=document.createElement('style');style.textContent='.fixture-root{margin:0!important;padding:0!important;max-width:none!important;height:100vh;display:flex;flex-direction:column}@media(max-width:850px){.fixture-root{height:auto;display:block}}.fixture-root>h1,.fixture-root>p,.fixture-root>button{display:none}';document.head.append(style);}
