import {mergeReaderDocument} from './pdfReaderState';
import type {DocumentLocation} from './pdfReaderState';
import {forwardRef,useEffect,useImperativeHandle,useRef,useState} from 'react';
import {BookOpen,ChevronRight,FileText,FileCode2,Globe,Import,Plus,Search,SlidersHorizontal,Tag,Folder,Library as LibraryIcon,Trash2,FolderOpen,Inbox} from 'lucide-react';
import {createDocument,desktop,fetchWebDocument,importDocuments,loadLibrary,saveSmartGroup,saveCollection,deleteCollection,organizeDocument,trashDocument,restoreDocument,purgeDocument,getLibraryDirectory,openLibraryLocation} from './bridge';
import {KnowledgeEditor} from './KnowledgeEditor';
import type {EditorHandle} from './KnowledgeEditor';
import {kindLabels,matchesGroup} from './knowledge';
import type {Library,LibraryDocument,SmartGroup,DocumentKind,Collection} from './knowledge';
import './library.css';
export interface LibraryHandle {flush:()=>Promise<void>}
const emptyGroup=():SmartGroup=>({id:'',name:'',revision:0,kind:null,tag:'',keyword:'',updatedDays:null});
const typeIcon=(kind:DocumentKind,size=16)=>{const Icon=kind==='web'?Globe:kind==='markdown'?FileCode2:FileText;return <Icon size={size} strokeWidth={1.75} aria-hidden="true"/>;};
const message=(e:unknown)=>e instanceof Error?e.message:String(e);
export const KnowledgeLibrary=forwardRef<LibraryHandle,{onNotice:(message:string)=>void;openLocation?:DocumentLocation|null}>(function KnowledgeLibrary({onNotice,openLocation},ref){
 const [library,setLibrary]=useState<Library>({documents:[],groups:[],collections:[],schemaVersion:3,error:null}),[loaded,setLoaded]=useState(false),[selected,setSelected]=useState<string|null>(null);
 const [kind,setKind]=useState<DocumentKind|null>(null),[tag,setTag]=useState(''),[groupId,setGroupId]=useState(''),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [newType,setNewType]=useState<'markdown'|'web'|null>(null),[title,setTitle]=useState(''),[url,setUrl]=useState(''),[content,setContent]=useState(''),[capture,setCapture]=useState(true),[groupDraft,setGroupDraft]=useState<SmartGroup|null>(null);
 const [collectionId,setCollectionId]=useState(''),[trash,setTrash]=useState(false),[unfiled,setUnfiled]=useState(false),[collectionDraft,setCollectionDraft]=useState<Collection|null>(null),[generation,setGeneration]=useState(0),[directory,setDirectory]=useState(''),[showStorage,setShowStorage]=useState(false);
 const [confirmation,setConfirmation]=useState<{operation:'trash'|'purge'|'collection';id:string;revision:number;name:string}|null>(null);
 const [location,setLocation]=useState<DocumentLocation|null>(null);
 const editor=useRef<EditorHandle>(null),changing=useRef(false);
 const selectedDocument=library.documents.find(d=>d.id===selected);
 useImperativeHandle(ref,()=>({flush:async()=>{await editor.current?.flush();}}));
 useEffect(()=>{let active=true;loadLibrary().then(data=>{if(active){setLibrary(data);setLoaded(true);}}).catch(reason=>{if(active){setError(message(reason));setLoaded(true);}});return()=>{active=false;};},[]);
 useEffect(()=>{if(loaded&&openLocation)select(openLocation.id,openLocation);},[loaded,openLocation]);
 function saved(doc:LibraryDocument){setLibrary(current=>({...current,documents:current.documents.map(d=>d.id===doc.id?mergeReaderDocument(d,doc):d)}));}
 function inserted(doc:LibraryDocument){setLibrary(current=>({...current,documents:[doc,...current.documents.filter(d=>d.id!==doc.id)]}));}
 function external(doc:LibraryDocument){saved(doc);setGeneration(n=>n+1);}

 async function action(work:(current?:LibraryDocument)=>Promise<void>){
  if(changing.current)return;changing.current=true;const handle=editor.current;handle?.beginMutation();setBusy(true);setError('');
  try{const current=await handle?.flush();await work(current);}catch(reason){setError(message(reason));}finally{handle?.endMutation();changing.current=false;setBusy(false);}
 }

 function select(id:string,nextLocation?:DocumentLocation){void action(async()=>{if(!library.documents.some(d=>d.id===id))throw new Error('链接指向的文档不存在');setConfirmation(null);setSelected(id);setLocation(nextLocation||null);const target=library.documents.find(d=>d.id===id);if(target?.deletedAt!=null){setTrash(true);setKind(null);setTag('');setGroupId('');setCollectionId('');setUnfiled(false);}});}
 function filter(next:()=>void){void action(async()=>{setCollectionId('');setTrash(false);setUnfiled(false);next();setSelected(null);setConfirmation(null);});}
 async function importFile(){await action(async()=>{const docs=await importDocuments();if(docs.length){docs.forEach(inserted);setCollectionId('');setTrash(false);setUnfiled(false);setKind(null);setTag('');setGroupId('');setSelected(docs[0].id);onNotice('文档已导入本地知识库，源文件保持不变');}});}
 async function create(){await action(async()=>{const doc=newType==='web'&&capture?await fetchWebDocument(url.trim()):await createDocument({title:title.trim(),kind:newType||'markdown',content,url:newType==='web'?url.trim():null,tags:[]});inserted(doc);setCollectionId('');setTrash(false);setUnfiled(false);setSelected(doc.id);setKind(null);setTag('');setGroupId('');setNewType(null);setTitle('');setContent('');setUrl('');onNotice(newType==='web'?'网页正文已保存，可离线阅读':'Markdown 文档已创建');});}
 async function saveGroup(){if(!groupDraft)return;await action(async()=>{const group=await saveSmartGroup(groupDraft);setLibrary(current=>({...current,groups:[...current.groups.filter(g=>g.id!==group.id),group]}));setGroupDraft(null);setCollectionId('');setTrash(false);setUnfiled(false);setGroupId(group.id);setKind(null);setTag('');setSelected(null);});}
 async function saveFolder(){if(!collectionDraft)return;await action(async()=>{const c=await saveCollection(collectionDraft);setLibrary(current=>({...current,collections:[...current.collections.filter(old=>old.id!==c.id),c]}));setCollectionDraft(null);});}
 function organize(ids:string[]){void action(async current=>{if(!current)throw new Error('请选择文档');external(await organizeDocument(current.id,current.revision,ids));onNotice('分类已更新，资料仅保存一份');});}
 function lifecycle(operation:'trash'|'restore'|'purge'){
  if(!selectedDocument)return;
  if(operation==='restore'){void action(async current=>{if(!current)throw new Error('请选择文档');external(await restoreDocument(current.id,current.revision));setTrash(false);setKind(null);setGroupId('');setTag('');setCollectionId('');setUnfiled(false);onNotice('文档已恢复，可继续编辑');});}
  else setConfirmation({operation,id:selectedDocument.id,revision:selectedDocument.revision,name:selectedDocument.title});
 }
 function confirm(){if(!confirmation)return;const request=confirmation;void action(async current=>{
  if(request.operation==='collection'){const updated=await deleteCollection(request.id,request.revision);setLibrary(updated);setGeneration(n=>n+1);if(!updated.collections.some(c=>c.id===collectionId))setCollectionId('');setCollectionDraft(null);onNotice('分类已删除，其中资料仍保留在知识库');}
  else {if(current?.id!==request.id)throw new Error('选中文档已改变，请重新确认');
   if(request.operation==='trash'){external(await trashDocument(current.id,current.revision));setSelected(null);onNotice('文档已移入回收站，可恢复');}
   else {const warning=await purgeDocument(current.id,current.revision);setLibrary(data=>({...data,documents:data.documents.filter(d=>d.id!==current.id)}));setSelected(null);onNotice(warning||'文档已永久删除');}
  }setConfirmation(null);
 });}
 async function storage(){if(!desktop)return;try{setDirectory(await getLibraryDirectory());setShowStorage(v=>!v);}catch(reason){setError(message(reason));}}
 const active=library.documents.filter(d=>d.deletedAt==null),trashed=library.documents.filter(d=>d.deletedAt!=null);
 const group=library.groups.find(g=>g.id===groupId),collection=library.collections.find(c=>c.id===collectionId),now=Date.now();
 const filtered=(trash?trashed:active).filter(d=>(!kind||d.kind===kind)&&(!tag||d.tags.includes(tag))&&(!group||matchesGroup(d,group,now))&&(!collectionId||(d.collectionIds||[]).includes(collectionId))&&(!unfiled||!(d.collectionIds||[]).length)&&matchesGroup(d,{keyword:query},now)).sort((a,b)=>b.updatedAt-a.updatedAt);
 const tags=[...new Set(active.flatMap(d=>d.tags))].sort();
 function folderRows(parent:string|null=null,depth=0):React.ReactNode{return library.collections.filter(c=>c.parentId===parent).map(c=><div key={c.id}><div className="library-group-row library-folder-row"><button style={{paddingLeft:8+depth*10}} className={collectionId===c.id?'selected':''} onClick={()=>filter(()=>{setCollectionId(c.id);setKind(null);setTag('');setGroupId('');})}><Folder size={14}/><span className="library-folder-name">{c.name}</span><span>{active.filter(d=>(d.collectionIds||[]).includes(c.id)).length}</span></button><button className="icon-button" aria-label={`管理分类 ${c.name}`} disabled={disabled} onClick={()=>setCollectionDraft({...c})}><SlidersHorizontal size={12}/></button></div>{depth<7&&folderRows(c.id,depth+1)}</div>);}
 const disabled=!desktop||busy||!!library.error||!loaded;
 return <section className="knowledge-library" aria-label="知识库">
  <div className="library-toolbar"><div><LibraryIcon size={19}/><span>{active.length} 篇文档</span><small>此设备上的独立知识库</small></div><button className="secondary-button compact" disabled={!desktop||busy} onClick={()=>void storage()}><FolderOpen size={16}/>存储位置</button><button className="secondary-button compact" disabled={disabled} onClick={()=>void importFile()}><Import size={14}/>导入文件</button><button className="secondary-button compact" disabled={disabled} onClick={()=>{setNewType('web');setCapture(true);}}><Globe size={14}/>保存网页</button><button className="primary-button compact" disabled={disabled} onClick={()=>{setNewType('markdown');setCapture(false);}}><Plus size={14}/>新建 Markdown</button></div>
  {showStorage&&<div className="library-storage"><FolderOpen size={16}/><div><strong>此设备上的资料库</strong><code>{directory}</code><small>文档信息、分类和版本保存在 library.json；PDF 副本保存在 library-blobs。备份时需包含整个目录。</small></div><button className="secondary-button compact" disabled={!desktop||busy} onClick={()=>void openLibraryLocation().catch(e=>setError(message(e)))}>在 Finder 中打开</button></div>}
  {confirmation&&<div className="library-confirmation" role="alertdialog" aria-label="确认资料操作"><div><strong>{confirmation.operation==='collection'?'删除分类':confirmation.operation==='trash'?'移入回收站':'永久删除'}「{confirmation.name}」？</strong><p>{confirmation.operation==='collection'?'此分类与子分类将被删除，其中的文档和附件会保留。':confirmation.operation==='trash'?'保存当前内容后移入回收站。文档、版本和附件可以恢复。':'文档、版本记录和库内附件将被删除，无法恢复；导入源文件保留。'}</p></div><button className="secondary-button compact" disabled={busy} onClick={()=>setConfirmation(null)}>取消</button><button className="secondary-button compact library-danger" disabled={disabled} onClick={confirm}>{busy?'正在处理…':'确认'+(confirmation.operation==='trash'?'移入回收站':'删除')}</button></div>}
  {collectionDraft&&<form className="library-group-form" aria-label="分类管理" onSubmit={e=>{e.preventDefault();void saveFolder();}}><strong>{collectionDraft.id?'管理分类':'新建分类文件夹'}</strong><label>分类名称<input required maxLength={128} value={collectionDraft.name} onChange={e=>setCollectionDraft({...collectionDraft,name:e.target.value})}/></label><label>父分类<select value={collectionDraft.parentId||''} onChange={e=>setCollectionDraft({...collectionDraft,parentId:e.target.value||null})}><option value="">资料库（顶层）</option>{library.collections.filter(c=>c.id!==collectionDraft.id).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{collectionDraft.id&&<button type="button" className="secondary-button compact library-danger" disabled={disabled} onClick={()=>setConfirmation({operation:'collection',id:collectionDraft.id,revision:collectionDraft.revision,name:collectionDraft.name})}><Trash2 size={14}/>删除分类</button>}<button type="button" className="secondary-button compact" disabled={busy} onClick={()=>setCollectionDraft(null)}>取消</button><button className="primary-button compact" disabled={disabled||!collectionDraft.name.trim()}>保存分类</button></form>}
  {(library.error||error)&&<div className="knowledge-error" role="alert">{library.error||error}</div>}
  {newType&&<form className="library-create-form" aria-label={newType==='web'?'保存网页':'新建 Markdown'} onSubmit={e=>{e.preventDefault();void create();}}><div><strong>{newType==='web'?'保存网页':'新建 Markdown'}</strong><button type="button" className="secondary-button compact" disabled={busy} onClick={()=>setNewType(null)}>取消</button></div>{newType==='web'&&<><label>来源网址<input autoFocus required placeholder="https://…" value={url} onChange={e=>setUrl(e.target.value)} type="url"/></label><label className="library-checkbox"><input type="checkbox" checked={capture} onChange={e=>setCapture(e.target.checked)}/>提取网页静态正文，不保存脚本或远端图片</label></>}{(!capture||newType==='markdown')&&<><label>标题<input autoFocus={newType==='markdown'} required value={title} maxLength={128} onChange={e=>setTitle(e.target.value)}/></label><label>{newType==='web'?'离线正文（可粘贴 Markdown）':'初始正文'}<textarea value={content} rows={4} onChange={e=>setContent(e.target.value)}/></label></>}<button className="primary-button compact" disabled={disabled||newType==='web'&&!url.trim()||!capture&&!title.trim()}>{busy?'正在保存…':newType==='web'?'保存网页':'创建文档'}</button>{newType==='web'&&<small>登录后或依赖脚本的页面可能无法抓取，可取消提取并粘贴正文。</small>}</form>}
  {groupDraft&&<form className="library-group-form" aria-label="智能分组条件" onSubmit={e=>{e.preventDefault();void saveGroup();}}><strong>{groupDraft.id?'编辑智能分组':'新建智能分组'}</strong><label>名称<input required maxLength={128} value={groupDraft.name} onChange={e=>setGroupDraft({...groupDraft,name:e.target.value})}/></label><label>文档类型<select value={groupDraft.kind||''} onChange={e=>setGroupDraft({...groupDraft,kind:e.target.value as DocumentKind||null})}><option value="">全部类型</option>{Object.entries(kindLabels).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label>标签<select value={groupDraft.tag} onChange={e=>setGroupDraft({...groupDraft,tag:e.target.value})}><option value="">不限标签</option>{tags.map(t=><option key={t}>{t}</option>)}</select></label><label>关键词<input value={groupDraft.keyword} maxLength={200} onChange={e=>setGroupDraft({...groupDraft,keyword:e.target.value})}/></label><label>最近更新<select value={groupDraft.updatedDays||''} onChange={e=>setGroupDraft({...groupDraft,updatedDays:e.target.value?Number(e.target.value):null})}><option value="">不限时间</option><option value="1">最近 24 小时</option><option value="7">最近 7 天</option><option value="30">最近 30 天</option></select></label><span>同时满足所有条件</span><button className="secondary-button compact" type="button" disabled={busy} onClick={()=>setGroupDraft(null)}>取消</button><button className="primary-button compact" disabled={disabled||!groupDraft.name.trim()}>保存分组</button></form>}
  <div className="library-columns">
   <aside className="library-organization" aria-label="文档分组"><button className={!kind&&!tag&&!groupId&&!collectionId&&!trash&&!unfiled?'selected':''} onClick={()=>filter(()=>{setKind(null);setTag('');setGroupId('');})}><BookOpen size={15}/>全部文档<span>{active.length}</span></button>{Object.entries(kindLabels).map(([id,label])=><button key={id} className={kind===id?'selected':''} onClick={()=>filter(()=>{setKind(id as DocumentKind);setTag('');setGroupId('');})}>{typeIcon(id as DocumentKind)}{label}<span>{active.filter(d=>d.kind===id).length}</span></button>)}<button className={unfiled?'selected':''} onClick={()=>filter(()=>{setUnfiled(true);setKind(null);setTag('');setGroupId('');})}><Inbox size={16}/>未分类<span>{active.filter(d=>!(d.collectionIds||[]).length).length}</span></button><button className={trash?'selected':''} onClick={()=>filter(()=>{setTrash(true);setKind(null);setTag('');setGroupId('');})}><Trash2 size={16}/>回收站<span>{trashed.length}</span></button><div className="library-section-heading"><span>分类文件夹</span><button aria-label="新建分类文件夹" disabled={disabled} onClick={()=>setCollectionDraft({id:'',name:'',parentId:collectionId||null,revision:0})}><Plus size={14}/></button></div>{folderRows()}{!library.collections.length&&<p>将同一资料加入多个分类。</p>}<div className="library-section-heading"><span>智能分组</span><button aria-label="新建智能分组" disabled={disabled} onClick={()=>setGroupDraft(emptyGroup())}><Plus size={14}/></button></div>{library.groups.map(g=><div className="library-group-row" key={g.id}><button className={groupId===g.id?'selected':''} onClick={()=>filter(()=>{setGroupId(g.id);setTag('');setKind(null);})}><Folder size={14}/>{g.name}<span>{active.filter(d=>matchesGroup(d,g,now)).length}</span></button><button aria-label={`编辑分组 ${g.name}`} className="icon-button" disabled={disabled} onClick={()=>setGroupDraft({...g})}><SlidersHorizontal size={12}/></button></div>)}{!library.groups.length&&<p>按标签、类型或关键词自动归集。</p>}<div className="library-section-heading"><span>标签</span><Tag size={12}/></div>{tags.map(t=><button key={t} className={tag===t?'selected':''} onClick={()=>filter(()=>{setTag(t);setKind(null);setGroupId('');})}><span className="library-tag-dot"/>{t}<span>{active.filter(d=>d.tags.includes(t)).length}</span></button>)}{!tags.length&&<p>在文档信息中添加标签。</p>}</aside>
   <section className="library-list" aria-label="文档列表"><label className="library-search"><Search size={14}/><input aria-label="搜索知识库" placeholder="搜索标题、标签和正文" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="library-list-heading"><strong>{trash?'回收站':unfiled?'未分类':collection?.name||group?.name||tag||kind&&kindLabels[kind]||'全部文档'}</strong><span>{filtered.length}</span></div><div className="library-document-list">{filtered.map(doc=><button className={`library-document-row ${selected===doc.id?'selected':''}`} key={doc.id} onClick={()=>select(doc.id)}><span className={`library-file-icon ${doc.kind}`}>{typeIcon(doc.kind,20)}</span><div><strong>{doc.title}</strong><p>{doc.kind==='pdf'?`${(doc.sizeBytes/1024/1024).toFixed(1)} MB · ${doc.content?'有备注':'本地 PDF'}`:doc.content.slice(0,65)||'空文档'}</p><span>{new Date(doc.updatedAt).toLocaleDateString('zh-CN')}{doc.tags.length?` · ${doc.tags.slice(0,2).join(', ')}`:''}{doc.draft?' · 待恢复草稿':''}</span></div><ChevronRight size={12}/></button>)}{!filtered.length&&<div className="library-list-empty">{loaded?'没有匹配的文档':'正在读取…'}</div>}</div><footer>PDF 检索标题、标签和备注</footer></section>
   {selectedDocument?<KnowledgeEditor key={`${selectedDocument.id}:${generation}:${selectedDocument.deletedAt!=null}`} ref={editor} locked={busy} collections={library.collections} onOrganize={organize} onLifecycle={lifecycle} location={location} document={selectedDocument} documents={library.documents} onSaved={saved} onNavigate={select} onNotice={onNotice}/>:<section className="library-welcome"><span><BookOpen size={32}/></span><h2>{library.documents.length?'选择一篇文档':'收集、连接、继续思考'}</h2><p>{desktop?'导入 PDF 与 Markdown，保存网页，并用标签和文档链接组织它们。':'在 Orbit 桌面 App 中导入文档、编辑 Markdown 和恢复历史版本。'}</p><div><span>本地保存</span><span>智能分组</span><span>版本恢复</span></div></section>}
  </div>
 </section>;
});
